feat: add bearer reader
OWASP-Benchmark/BenchmarkUtils pull request #59
Opened 2023-11-15 16:28 UTC by cfabianski

Add Bearer Reader

https://github.com/bearer/bearer

Requires this one to be released https://github.com/Bearer/bearer/pull/1401

2023-11-15 21:05 UTC, darkspirit510 requested changes

2023-11-16 08:54 UTC, cfabianski commented on plugin/src/test/java/org/owasp/benchmarkutils/score/parsers/BearerReaderTest.java
> + * @author Sascha Knoop
Thanks @darkspirit510 
It's fixed now :)

2023-11-16 08:54 UTC, cfabianski commented on plugin/src/main/java/org/owasp/benchmarkutils/score/parsers/BearerReader.java
> +        /*
Thanks @darkspirit510 
Yeah I removed it. Test case is more than enough :)

2023-11-20 19:13 UTC, davewichers commented
@darkspirit510 - You OK with this MR now so I can merge it?

2023-11-21 18:31 UTC, darkspirit510 commented
@davewichers the code looks good, but as you wrote in https://github.com/OWASP-Benchmark/BenchmarkJava/pull/214, I did not yet manage to create/test with a real file.

2023-11-21 20:06 UTC, darkspirit510 commented
@davewichers I just build the code from Bearer's repo and was able to scan the file.

2023-11-21 20:07 UTC, darkspirit510 approved these changes

2023-11-21 20:12 UTC, merged

2023-12-12 13:38 UTC, cfabianski commented
> @davewichers I just build the code from Bearer's repo and was able to scan the file.

Hey @darkspirit510 thanks for this and sorry for the lack of response :(
Yeah the release went probably after you tried https://github.com/Bearer/bearer/releases/tag/v1.31.0